# Generated by Django 4.0.2 on 2022-06-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='dueño',
        ),
        migrations.DeleteModel(
            name='Dueño',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
